Repository rswc/bem, pull requests merged in 2023-01, with the labels that each got.

#24 Refactor klasy coordinator po code-review
  coordinator/src/accept.cpp
  coordinator/src/handler.cpp
  coordinator/src/main.cpp
  coordinator/src/state.h
Labels: enhancement

#25 Add error warnings to cmake
  CMakeLists.txt
Labels: enhancement, question

#35 Good Looking
  README.md
  common/CMakeLists.txt
  common/src/baseMessage.h
  common/src/gamelist.cpp
  common/src/gamelist.h
  common/src/messageFactory.cpp
  common/src/messages.h
  common/src/pingMessage.cpp
  common/src/pongMessage.cpp
  common/src/pongMessage.h
  common/src/result.cpp
  common/src/result.h
  common/src/resultMessage.cpp
  common/src/resultMessage.h
  common/src/task.cpp
  common/src/task.h
  common/src/taskMessage.cpp
  common/src/taskMessage.h
  common/src/taskNotifyMessage.cpp
  common/src/taskNotifyMessage.h
  config/coordinator.json
  config/node.json
  coordinator/src/accept.cpp
  coordinator/src/config.cpp
  coordinator/src/config.h
  coordinator/src/handler.cpp
  coordinator/src/main.cpp
  coordinator/src/node.cpp
  coordinator/src/node.h
  coordinator/src/readNode.cpp
  coordinator/src/state.h
  node/CMakeLists.txt
  node/src/communication.cpp
  node/src/communication.h
  node/src/config.cpp
  node/src/config.h
  node/src/execute.cpp
  node/src/execute.h
  node/src/graceful.cpp
  node/src/graceful.h
  node/src/main.cpp
  node/src/protocol.cpp
  node/src/protocol.h
  node/src/read.cpp
  node/src/read.h
  node/src/state.cpp
  node/src/state.h
  node/src/write.cpp
  node/src/write.h
Labels: enhancement

#38 Feature/aggregation
  common/src/invalidMessage.cpp
  common/src/result.h
  common/src/task.h
  coordinator/src/handler.cpp
  coordinator/src/main.cpp
  coordinator/src/state.h
Labels: enhancement, coordinator, common

#45 Błędy po oddaniu projektu
  coordinator/src/main.cpp
  coordinator/src/readNode.cpp
  coordinator/src/state.h
  coordinator/src/writeNode.cpp
  node/src/communication.cpp
  node/src/graceful.cpp
Labels: bug, coordinator
